Add automated scripts for installfest and update INSTALLFEST.md
ga-wdi-boston/orientation pull request #256
Opened 2017-04-26 15:17 UTC by sdavidson140

I automated everywhere that I could and updated the INSTALLFEST.md to reflect changes.

Had trouble automating entire 'linking with github process' using ssh-keygen
   I found a flag to skip prompting the user for password, but I am still prompted to enter/confirm 
  output filename even when specifying so in the command.
  However, I automated the rest of it.

I removed the sections from INSTALLFEST.md for installing rbenv, Ruby, and postgres, but still included the scripts in config/

Fixed Atom autocomplete issue we discussed, will close issue after these changes are merged

2017-04-26 16:27 UTC, gaand requested changes
Why are there separate git scripts?
Are we using linux brew for linux?

Please have a look and let me know if you have questions.

2017-04-26 16:27 UTC, gaand commented on config/atom.sh
> +#!/usr/bin/env bash
Is there an issue about using cask to install Atom?  Would that make it possible to have a more comprehensive script?  Also, where's a check to see if the commands are available?

2017-04-26 16:27 UTC, gaand commented on config/bash.sh
> +  echo '/\/usr\/local\/bin/\nd\nwq' | sudo ed /etc/paths
There's definitely an issue saying not to do this anymore.

2017-04-26 16:27 UTC, gaand commented on config/git.sh
> +if which git; then
This test is insufficient. Git is installed on macOS by default.

2017-04-26 16:27 UTC, gaand commented on config/npm.sh
> +npm install --global jshint jsonlint grunt-cli remark-lint jscs bower phantomjs-prebuilt
This is not the correct set of global packages.

2017-04-26 16:27 UTC, gaand commented on config/nvm.sh
> +  export NVM_DIR="/home/$(whoami)/.nvm"
I believe this is unnecessary if nvm is installed and in the path.

2017-04-26 16:27 UTC, gaand commented on config/nvm.sh
> +  export NVM_DIR=~/.nvm
As the above

2017-04-26 16:27 UTC, gaand commented on config/postgres.sh
> +  mkdir -p ~/Library/LaunchAgents
Is this actually necessary?

2017-04-26 16:27 UTC, gaand commented on config/rbenv.sh
> +if which rvm; then
Destructive actions should warn the user

2017-04-26 16:27 UTC, gaand commented on config/xcode.sh
> +if which xcode-select; then
I'm not sure why this would work.

2017-04-26 19:16 UTC, sdavidson140 commented
I consolidated git_config.sh with git.sh.
There is still another script because ssh-keygen needs to be done in between. Even if I explicitly set password and file, I still get prompted for file.

After researching the export NVM_DIR, I continually found issues with nvm command not working unless you do the export

removing rvm now prompts the user for a y/n

I couldn't find an issue about installing atom with cask. This would help the automation process, but I want to make sure that everything else is functional / there's no other issues before doing that.

There are many open issues. I commented and addressed the ones I saw as imperative for Friday, but will be clearing that.

2017-04-27 03:03 UTC, sdavidson140 commented
Tested all scripts, fixing any errors encountered. Consolidated two of the git scripts. Looked more into installing atom with cask, and I'm not sure that it would speed up the process. Also edited the INSTALLFEST.md doc to reflect changes.

2017-04-27 14:23 UTC, jrhorn424 commented on INSTALLFEST.md
> +1.  Move Atom from downloads to the Application directory.
This step is very important. Without it, the command line tool installation will claim to work when it does not actually work. This is due to sandboxing on macOS.

2017-04-27 14:24 UTC, jrhorn424 commented on config/atom.sh
> +#!/usr/bin/env bash
> Also, where's a check to see if the commands are available?

I agree, this should be added before merge IMO.

2017-04-27 14:27 UTC, jrhorn424 commented on config/nvm.sh
> +nvm install --lts=boron || nvm install 6.9.4
Boron is now at 6.10.2. I'm not sure what we want to do about that @gaand.

2017-04-27 17:49 UTC, gaand requested changes
Linux brew is important.

2017-04-27 17:49 UTC, gaand commented on config/rbenv.sh
> +echo bundler > ~/.rbenv/default-gems
Destructive.

2017-04-27 17:49 UTC, gaand commented on config/rbenv.sh
> +read -p "# expecting message 'rbenv 1.1.0'
Check this directly, don't prompt

2017-04-27 19:22 UTC, sdavidson140 commented on config/atom.sh
> +#!/usr/bin/env bash
Cask will only work for macOSX. Tested process in Ubuntu machine

2017-04-27 19:23 UTC, sdavidson140 commented on config/rbenv.sh
> +if which rvm; then
Now prompt user for (y/n). Only remove if yes

2017-04-27 19:27 UTC, sdavidson140 commented on INSTALLFEST.md
> +1.  Move Atom from downloads to the Application directory.
I moved these steps and the atom part to end of installfest. cask will work to install on mac, but not linux

2017-04-27 19:46 UTC, sdavidson140 commented on config/rbenv.sh
> +read -p "# expecting message 'rbenv 1.1.0'
This is now automated

2017-04-27 20:58 UTC, sdavidson140 commented
Looked into cask for installing atom, but it only works on mac. I updated INSTALLFEST.md to tell them to run `brew cask install atom` for mac (kept old command for linux). I will test scripts again tonight on linux and mac just to make sure we're all good for tomorrow. 

Let me know if anything is unclear.

2017-04-28 14:25 UTC, merged